---
title: Anhang I
subtitle: "Weiterführende Methoden der Statistik vor allem, aber nicht exklusiv, für den Bereich Ökologie können in einem Individual Spezialisation Module (ISM) gelernt werden:"
---


Im Rahmen eine 3 ECTS ISM könnt ihr euch im geleiteten Selbststudium vertiefte Statistik-Kenntnisse mit R aneignen. Dieser Kurs baut auf den Statistikteilen in «Research Methods» auf und richtet sich primär an Studierende, die mit ökologischen Daten aus der Vegetations-, Tier- oder Gewässerökologie arbeiten, kann aber auch für andere ENR-Studierende nützlich sein. Es werden Unterrichtsmaterialien auf Englisch und auf Deutsch zu Verfügung gestellt.

Es werden vor allem die folgenden Themen bearbeitet:

- Vertiefung mixed effect models (LMMs, GLMMs) •
- Nicht-lineare Regressionen •
- Vertiefung Ordinationstechniken (DCA, NMDS, passive Projektion von Umweltvariablen, «constrained» Ordinationen wie RDA) •
- Agglomerative Clusteranalysen •
- Umfassende Biodiversitätsanalysen (beta- und gamma-Diversität, funktionelle und phylogenetische Diversität) •

Dazu können in Absprache mit den Studierenden ausgewählte weitere Bereiche kommen, etwa:

- Generalized additive models (GAMs) und Glättungsfunktionen •
- Diagnostische Arten (IndVal, phi-Werte) •
- Regression trees •
- Structural equation models (SEMs) •

Für den Leistungsnachweis ist eine Erfahrungsnote in Form von zwei semesterbegleitenden Hausarbeiten vorgesehen.

[Jürgen Dengler](http://deng@zhaw.ch/) und Stefan Widmer leiten den Selbststudiumskurs und steht euch für weitere Informationen und Fragen gerne zur Verfügung.

## Anhang II

