<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistik 1 – Statistik mit R für Umweltwissenschaftler:innen</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Statistik_2.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-3f61aac59b63c3a2d0e87c59ee7d0662.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-da5c885aecf6ad2e4d411c4770d4d372.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="custom_styles/html/style.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Statistik_1.html"><span class="chapter-title">Statistik 1</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/zhaw/zhaw_lsfm_iunr_schwarz.jpg" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./images/zhaw/zhaw_lsfm_iunr_schwarz.jpg" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Research Methods</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ResearchMethods-ZHAW/Statistik" title="Quellcode" class="quarto-navigation-tool px-1" aria-label="Quellcode"><i class="bi bi-github"></i></a>
    <a href="./Statistik_Script.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Statistik_1.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Statistik 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Statistik_2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Statistik 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Statistik_3.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Statistik 3</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Statistik_4.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Statistik 4</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Statistik_5.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Statistik 5</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Statistik_6.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Statistik 6</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Statistik_7.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Statistik 7</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Statistik_8.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Statistik 8</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Anhang.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Anhang</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul class="collapse">
  <li><a href="#die-rolle-der-statistik-beim-hypothesengenerieren-und--testen" id="toc-die-rolle-der-statistik-beim-hypothesengenerieren-und--testen" class="nav-link active" data-scroll-target="#die-rolle-der-statistik-beim-hypothesengenerieren-und--testen">Die Rolle der Statistik beim Hypothesengenerieren und -testen</a></li>
  <li><a href="#statistische-implementierung-des-hypothesentestens-am-beispiel-des-t-tests" id="toc-statistische-implementierung-des-hypothesentestens-am-beispiel-des-t-tests" class="nav-link" data-scroll-target="#statistische-implementierung-des-hypothesentestens-am-beispiel-des-t-tests">Statistische Implementierung des Hypothesentestens (am Beispiel des <em>t</em>-Tests)</a></li>
  <li><a href="#t-test-für-eine-metrische-variable-im-vergleich-von-zwei-gruppen" id="toc-t-test-für-eine-metrische-variable-im-vergleich-von-zwei-gruppen" class="nav-link" data-scroll-target="#t-test-für-eine-metrische-variable-im-vergleich-von-zwei-gruppen"><em>t</em>-Test (für eine metrische Variable im Vergleich von zwei Gruppen)</a></li>
  <li><a href="#binomial-test-für-die-häufigkeitsverteilung-einer-binomialen-variablen" id="toc-binomial-test-für-die-häufigkeitsverteilung-einer-binomialen-variablen" class="nav-link" data-scroll-target="#binomial-test-für-die-häufigkeitsverteilung-einer-binomialen-variablen">Binomial-Test (für die Häufigkeitsverteilung einer binomialen Variablen)</a></li>
  <li><a href="#möglichkeiten-zwei-stichproben-zu-vergleichen-und-implikationen-für-das-samplingdesign" id="toc-möglichkeiten-zwei-stichproben-zu-vergleichen-und-implikationen-für-das-samplingdesign" class="nav-link" data-scroll-target="#möglichkeiten-zwei-stichproben-zu-vergleichen-und-implikationen-für-das-samplingdesign">Möglichkeiten, zwei Stichproben zu vergleichen, und Implikationen für das Samplingdesign</a></li>
  <li><a href="#chi-quadrat--bzw.-fishers-test-für-die-assoziation-zweier-binomialer-variablen" id="toc-chi-quadrat--bzw.-fishers-test-für-die-assoziation-zweier-binomialer-variablen" class="nav-link" data-scroll-target="#chi-quadrat--bzw.-fishers-test-für-die-assoziation-zweier-binomialer-variablen">Chi-Quadrat- bzw. Fishers Test (für die Assoziation zweier binomialer Variablen)</a></li>
  <li><a href="#wie-berichtet-man-statistische-ergebnisse" id="toc-wie-berichtet-man-statistische-ergebnisse" class="nav-link" data-scroll-target="#wie-berichtet-man-statistische-ergebnisse">Wie berichtet man statistische Ergebnisse?</a></li>
  <li><a href="#weiterführende-literatur" id="toc-weiterführende-literatur" class="nav-link" data-scroll-target="#weiterführende-literatur">Weiterführende Literatur</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ResearchMethods-ZHAW/Statistik/edit/main/Statistik_1.qmd" class="toc-action"><i class="bi bi-github"></i>Seite editieren</a></li><li><a href="https://github.com/ResearchMethods-ZHAW/Statistik/issues/new" class="toc-action"><i class="bi empty"></i>Problem melden</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Statistik 1</span></h1>
<p class="subtitle lead">Grundlagen der Statistik</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In Statistik 1 lernen die Studierenden, was (Inferenz-) Statistik im Kern leistet und warum sie für wissenschaftliche Erkenntnis (in den meisten Disziplinen) unentbehrlich ist. Nach einer Wiederholung der Rolle von Hypothesen wird erläutert, wie Hypothesentests in der <em>frequentist</em>-Statistik umgesetzt werden, einschliesslich <em>p</em>-Werten und Signifikanz-Levels. Die praktische Statistik beginnt mit den beiden einfachsten Fällen, dem Chi-Quadrat-Test für die Assoziation zwischen zwei kategorialen Variablen und dem -Test auf Unterschiede in Mittelwerten zwischen zwei Gruppen. Abschliessend beschäftigen wir uns damit, wie man Ergebnisse statistischer Analysen am besten in Abbildungen, Tabellen und Text darstellt.</p>
<section id="lernziele" class="level4">
<h4 class="anchored" data-anchor-id="lernziele">Lernziele</h4>
<section id="ihr" class="level5">
<h5 class="anchored" data-anchor-id="ihr">Ihr…</h5>
<ul>
<li>versteht, was Statistik im Kern leistet und warum Statistik für wissenschaftliche Erkenntnis (in den meisten Disziplinen) unentbehrlich ist;</li>
<li>könnt Angaben zu p-Werten oder Signifikanzlevels kritisch würdigen;</li>
<li>wisst, wann man einen <em>t</em>-Test, einen Chi-Quadrat-Test oder einen Binomial-Test verwendet und wie man das praktisch in R durchführt;</li>
<li>versteht, dass die räumliche und zeitliche Anordnung von Beobachtungen bestimmt, welchen Test man verwenden kann; und</li>
<li>habt eine grundlegende Idee, worauf es beim Berichten statistischer Ergebnisse, insbesondere in Abbildungen ankommt.</li>
</ul>
</section>
</section>
<section id="warum-brauchen-wir-statistik" class="level4">
<h4 class="anchored" data-anchor-id="warum-brauchen-wir-statistik">Warum brauchen wir Statistik?</h4>
</section>
<section id="ein-beispiel" class="level4">
<h4 class="anchored" data-anchor-id="ein-beispiel">Ein Beispiel</h4>
<p>Ich möchte die grundlegende Notwendigkeit von Statistik mit einem fiktiven Beispiel visualisieren. Gehen wir von einer einfachen Frage aus dem Zierpflanzenbau aus:</p>
<p><em>Unterscheiden sich zwei verschiedene Sorten (Cultivare) in der Blütengrösse?</em></p>
<div class="quarto-layout-panel" data-layout-nrow="1">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Statistik_Skript _v.41_SW/_page_8_Picture_0.jpeg" class="img-fluid figure-img"></p>
<figcaption>Sorte A</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Statistik_Skript _v.41_SW/_page_8_Picture_1.jpeg" class="img-fluid figure-img"></p>
<figcaption>Sorte B</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Um diese Frage zu beantworten, vermessen wir die Blüten der beiden abgebildeten Individuen:</p>
<ul>
<li>Individuum A: 20 cm<sup>2</sup></li>
<li>Individuum B: 12 cm<sup>2</sup></li>
</ul>
<p>Mithin wäre unsere naive Antwort auf die Eingangsfragen: <strong>Ja, die Blüten von Sorte A sind grösser als jene von B</strong>. Wir können sogar sagen, um wie viel grösser (8 cm<sup>2</sup> oder 67 %).</p>
<p>Nun haben Pflanzen (wie fast alle Objekte, mit denen wir uns beschäftigen, mit Ausnahme vielleicht von Elementarteilchen) eine gewisse Variabilität:</p>
<p><img src="Statistik_Skript _v.41_SW/_page_9_Picture_0.jpeg" class="img-fluid"></p>
<p>Folglich ist es sinnvoller, für die Beantwortung der Frage jeweils mehrere Individuen zu vermessen. Wir greifen nun 10 Individuen jeder Sorte heraus und erzielen folgende Messergebnisse:</p>
<ul>
<li>Individuen A1-A10 [cm<sup>2</sup>]: 20; 19; 25; 10; 8; 15; 13; 18; 11; 14</li>
<li>Individuen B1–B10 [cm<sup>2</sup>]: 12; 15; 16; 7; 8; 10; 12; 11; 13; 10</li>
</ul>
<p>Wir erhalten für A einen Mittelwert von 15.3 cm<sup>2</sup> und für B einen Mittelwert von 11.4 cm<sup>2</sup> (was wir einfach in Excel ausrechnen können). <strong>Wir schliessen daher, dass die Blüten von A im Mittel 3.9</strong> cm<sup>2</sup> grösser sind als jene von B.</p>
<p>Wir könnten uns also zufrieden zurücklehnen und unserem Ergebnis, das wir mit etwas <strong>deskriptiver Statistik</strong> (Mittelwerte) erzielt haben, vertrauen. Wo liegt der Haken? Wir haben nicht alle existierenden Individuen der Sorten A und B vermessen (die “Grundgesamtheit”), sondern nur eine Stichprobe von jeweils 10 Individuen. Nun könnte es sein, dass KollegInnen von uns die gleiche Untersuchung mit jeweils anderen Stichproben von je 10 Individuen durchgeführt haben, etwa folgendermassen (mit ihren jeweiligen Schlussfolgerungen):</p>
<section id="mess-serie-1" class="level5">
<h5 class="anchored" data-anchor-id="mess-serie-1">Mess-Serie 1:</h5>
<ul>
<li>Individuen A1–A10 [cm<sup>2</sup>]: 20; 19; 25; 10; 8; 15; 13; 18; 11; 14</li>
<li>Individuen B1-B10 [cm<sup>2</sup>]: 12; 15; 16; 7; 8; 10; 12; 11; 13; 10</li>
<li>Ergebnis: A = 15.3; B = 11.4; A B = 3.9 cm<sup>2</sup> <span class="math inline">\(\rightarrow\)</span> <strong>A ist grösser als B</strong></li>
</ul>
</section>
<section id="mess-serie-2" class="level5">
<h5 class="anchored" data-anchor-id="mess-serie-2">Mess-Serie 2:</h5>
<ul>
<li>Individuen A1–A10 [cm<sup>2</sup>]: 12; 19; 17; 10; 8; 13; 11; 15; 11; 9</li>
<li>Individuen B1-B10 [cm<sup>2</sup>]: 12; 15; 16; 7; 8; 10; 12; 11; 13; 10</li>
<li>Ergebnis: A = 12.5; B = 11.4; A B = 1.2 cm<sup>2</sup> <span class="math inline">\(\rightarrow\)</span> <strong>A ist (wenig) grösser als B</strong></li>
</ul>
</section>
<section id="mess-serie-3" class="level5">
<h5 class="anchored" data-anchor-id="mess-serie-3">Mess-Serie 3:</h5>
<ul>
<li>Individuen A1–A10 [cm<sup>2</sup>]: 20; 19; 25; 10; 8; 15; 13; 15; 11; 14</li>
<li>Individuen B1-B10 [cm<sup>2</sup>]: 12; 15; 16; 7; 8; 10; 12; 11; 13; 10</li>
<li>Ergebnis: A = 11.0; B = 11.0; A B = 0.0 cm<sup>2</sup> → A ist gleich gross wie B</li>
</ul>
</section>
<section id="mess-serie-4" class="level5">
<h5 class="anchored" data-anchor-id="mess-serie-4">Mess-Serie 4:</h5>
<ul>
<li>Individuen A1–A10 [cm<sup>2</sup>]: 20; 19; 25; 10; 8; 15; 13; 18; 11; 14</li>
<li>Individuen B1–B10 [cm<sup>2</sup>]: 12; 15; 16; 16; 14; 10; 12; 11; 13; 10</li>
<li>Ergebnis: A = 11.0; B = 12.9; A B = 1.9 cm<sup>2</sup> <span class="math inline">\(\rightarrow\)</span> <strong>A ist kleiner als B</strong></li>
</ul>
<p>Wer hat nun Recht? Um das zu beantworten, benötigen wir die <strong>schliessende Statistik</strong> (Inferenzstatistik).</p>
</section>
<section id="fazit" class="level5">
<h5 class="anchored" data-anchor-id="fazit">Fazit</h5>
<ul>
<li>In der Regel wollen wir nicht wissen, ob ein einzelnes Individuum der Sorte A sich von einem einzelnen Individuum der Sorte B unterscheidet.</li>
<li>Meist interessiert uns, ob sich die Sorte A als solche von der Sorte B unterscheidet.</li>
<li>Da es in der Regel nicht möglich ist, sämtliche existierenden Individuen beider Sorten (<strong>Grundgesamtheiten</strong>; engl. <em>populations</em>) zu vermessen, vermessen wir die Individuen in zwei <strong>Stichproben</strong> (engl. <em>samples</em>).</li>
<li>Die Inferenzstatistik sagt uns dann, wie wahrscheinlich ein festgestellter Unterschied in den Mittelwerten der Stichproben einem tatsächlichen Unterschied in den Mittelwerten der Grundgesamtheiten entspricht.</li>
</ul>
</section>
</section>
<section id="warum-mit-r" class="level4">
<h4 class="anchored" data-anchor-id="warum-mit-r">Warum mit R?</h4>
<p>Zugegeben: wir haben euch nicht gefragt…</p>
<p><img src="Statistik_Skript _v.41_SW/_page_11_Picture_0.jpeg" class="img-fluid"></p>
</section>
<section id="was-spricht-dagegen" class="level4">
<h4 class="anchored" data-anchor-id="was-spricht-dagegen">Was spricht dagegen?</h4>
<p>Auf den ersten Blick mag aus eurer Sicht ja einiges dagegensprechen</p>
<ul>
<li><strong>keine GUI</strong> (grafische Benutzeroberfläche) zum Klicken</li>
<li>auf Englisch</li>
<li><strong>schwerer</strong> zu erlernen</li>
</ul>
</section>
<section id="was-spricht-dafür" class="level4">
<h4 class="anchored" data-anchor-id="was-spricht-dafür">Was spricht dafür?</h4>
<ul>
<li>R ist <strong>kostenlos &amp; open source</strong> (unabhängig von teuren Lizenzen)</li>
<li>R ist extrem <strong>leistungsfähig</strong> und immer <strong>up-to-date</strong> (da Tausende “ehrenamtlich” mitprogrammieren)</li>
<li>R ist nah an den <strong>speziellen Bedürfnissen</strong> der einzelnen Disziplinen (durch zahlreiche spezielle <em>Packages</em>)</li>
<li>R “zwingt” die Benutzenden dazu, ihr <strong>statistisches Vorgehen zu durchdenken</strong> (was zu besseren Ergebnissen führt)</li>
<li>R gewährleistet eine sehr <strong>gute Dokumentation</strong> des eigenen Vorgehens (“Reproduzierbarkeit”), da der geschriebene R Code anders als eine Klickabfolge in einem kommerziellen Statistikprogramm mit GUI eingesehen und erneut durchgeführt werden kann</li>
<li>R ist effizient, da man Code, den man einmal entwickelt hat, <strong>immer wieder verwenden bzw. für neue Projekte anpassen</strong> kann</li>
<li>Für R gibt es <strong>umfangreiche Hilfe im Internet</strong> (googlen, spezielle Foren,…)</li>
</ul>
</section>
<section id="fazit-1" class="level4">
<h4 class="anchored" data-anchor-id="fazit-1">Fazit</h4>
<p>Der Kursleiter (J.D.) hat Statistik nicht in seinem Studium gelernt und es sich später im Laufe seiner Forscherlaufbahn mühsam sich selbst beigebracht. Damals gab es noch kein R. Dafür gab es teure kommerzielle Statistikprogramme wie SPSS und STATISTICA, durch die man sich mit einer grafischen Benutzeroberfläche durchklicken konnte und am Ende ein Ergebnis bekam. Nicht immer war ganz klar, was das Programm da gerechnet hatte, aber immerhin bekam man mit relativ wenigen Klicks ein numerisches Ergebnis oder eine Abbildung (oft allerdings in bescheidenem Layout) heraus. Häufig musste man aber erleben, dass das gewünschte statistische Verfahren im jeweiligen Programm in der gewünschten Version nicht implementiert war oder ein teures Zusatzpaket nötig gewesen wäre, das die eigene Universität nicht erworben hatte. Und wenn man dann an eine andere Universität wechselte, musste man oft feststellen, dass dort ein anderes Statistikprogramm erworben und genutzt wurde, für das man viele Dinge umlernen musste. Ganz zu schweigen von Zeiten ausserhalb einer Hochschule, wenn man keinen Zugriff auf ein kommerzielles Statistikprogramm hatte.</p>
<p>Aus dieser Sicht könnt ihr euch also glücklich schätzen, dass es heute R gibt und so leistungsfähig ist wie nie zuvor und auch dass das IUNR in der Ausbildung im Bachelor- und Masterlevel konsequent auf R setzt. Während es auf den ersten Blick vielleicht schwieriger erscheinen mag als die Benutzung von SPSS oder STATISTICA, bin ich überzeugt, dass ein Statistikkurs mit R euch bei gleichem Aufwand ein anderes Verständnislevel für Statistik ermöglichen wird als es Statistikkurse zu meiner Studienzeit taten. Nebenher bekommt ihr noch ein implizites Verständnis wie Algorithmen funktionieren, auch nicht ganz unwichtig in einer zunehmend digitalen Welt.</p>
</section>
<section id="die-rolle-von-hypothesen-in-der-wissenschaft" class="level3">
<h3 class="anchored" data-anchor-id="die-rolle-von-hypothesen-in-der-wissenschaft">Die Rolle von Hypothesen in der Wissenschaft</h3>
<section id="rekapitulation" class="level4">
<h4 class="anchored" data-anchor-id="rekapitulation">Rekapitulation</h4>
<p>Im Methodenmodul und sicher auch in euren vorausgehenden Studiengängen habt ihr euch bereits mit Hypothesen beschäftigt. Daher beginnen wir mit einem Arbeitsauftrag (allein oder im Austausch mit KommilitonInnen):</p>
<section id="arbeitsauftrag" class="level5">
<h5 class="anchored" data-anchor-id="arbeitsauftrag">Arbeitsauftrag</h5>
<p>Formuliert jeweils in einem Satz die folgenden Punkte:</p>
<ul>
<li>Eine beispielhafte Aussage, die den Ansprüchen an eine Hypothese genügt</li>
<li>Eine beispielhafte Aussage, die keine Hypothese ist</li>
</ul>
</section>
</section>
<section id="was-ist-eine-hypothese" class="level4">
<h4 class="anchored" data-anchor-id="was-ist-eine-hypothese">Was ist eine Hypothese?</h4>
<p>Es gibt in der Literatur wie fast immer in der Wissenschaft verschiedene Formulierungen. Ich schlage die folgende vor:</p>
<p>Eine Hypothese ist eine aus einer allgemeinen Theorie abgeleitete Vorhersage für eine spezifische Situation.</p>
<p>Leider wird der Begriff “Hypothese” heutzutage in der Wissenschaft “inflationär” und aus meiner Sicht sogar häufig falsch verwendet.</p>
<p>Zweifelhaft sind “ad hoc”-Hypothesen auf der Basis einer Vorabuntersuchung bzw. eines “Bauchgefühls”, aber ohne eine Erklärung des für das vorhergesagte Ergebnis verantwortlichen Mechanismus (also letztlich ohne Theorie dahinter). Wissenschaftstheoretisch sollte man nie dieselben Daten zum Aufstellen und zum Testen einer Hypothese verwenden!</p>
<p>Gänzlich falsch sind angebliche “Hypothesen”, die nachträglich aus den schon erzielten Ergebnissen abgeleitet werden.</p>
<p>Warum findet man in der wissenschaftlichen Literatur wie auch in studentischen Arbeiten so viele “Hypothesen”, die wissenschaftstheoretisch dem Konzept einer Hypothese nicht gerecht werden? Der Grund dürfte darin liegen, dass viele von der Annahme geleitet werden, dass nur eine hypothesentestende Forschung eine gute/richtige Forschung ist. Tatsächlich ist aber hypothesengenierende Forschung genauso wichtig und richtig wie hypothesentestende Forschung. Es gilt also:</p>
<p>Wenn das Vorwissen nicht für eine <strong>plausibel begründete Hypothese</strong> ausreicht (<strong>hypothesentestende Forschung</strong>), formuliert man das Forschungsthema korrekterweise besser als <strong>offene Frage</strong> (<strong>hypothesengenerierende Forschung</strong>).</p>
<p>Dabei können offene Fragen meist mit (fast) den gleichen statistischen Verfahren adressiert werden wie Hypothesen. Allerdings sollten Hypothesen konkret sein, also nicht “A unterscheidet sich von B”, sondern entweder “A ist grösser als B” oder “A ist kleiner als B”. Hier würde also im Fall einer Hypothese ein einseitiger Test, im Fall einer offenen Frage ein zweiseitiger Test zur Anwendung kommen. Dazu aber später mehr.</p>
</section>
<section id="wissenschaftliches-arbeiten-in-a-nutshell" class="level4">
<h4 class="anchored" data-anchor-id="wissenschaftliches-arbeiten-in-a-nutshell">Wissenschaftliches Arbeiten (<em>in a nutshell</em>)</h4>
<p>Wenn wir modernes wissenschaftliches Arbeiten knapp visualisieren, ergibt sich folgendes Bild:</p>
<p><img src="images/nutshell.png" class="img-fluid"></p>
<p>Bei den ersten Schritten von den Beobachtungen bis zur Spekulation über die Musterursachen handelt es sich um hypothesengenerierende Forschung. Erst wenn man regelmässig, ähnliche Befunde hat, macht das Formulieren einer echten Hypothese Sinn, die nicht nur das gefundene Muster vorhersagt, sondern auch einen Mechanismus bereithält, der erklärt, wie es zustande gekommen ist. Eine solche Hypothese kann dann in einer neuen Untersuchung (mit neuen Daten!) getestet werden, die spezifisch darauf ausgelegt ist, alternative Erklärungsmöglichkeiten auszuschliessen (“Experiment”). Hypothesengenierende und hypothesentestende Forschung sind im modernen Forschungsablauf also beide gleichermassen nötig, aber in der Regel getrennt voneinander.</p>
<p>In einer Forschungsarbeit, die für das Testen einer zuvor in anderen Arbeiten erarbeiteten Hypothese, entwickelt wurde (“Experiment”), kann das Ergebnis entweder eine Bestätigung oder eine Falsifizierung sein. Wichtig ist, dass eine einmalige Bestätigung keine Verifizierung einer Hypothese ist, während eine einmalige Falsifizierung zur Widerlegung genügt. <strong>Eine Verifizierung einer Hypothese in einem absoluten Sinn ist grundsätzlich nicht möglich, absolute Wahrheit gibt es in der Wissenschaft nicht!</strong> Wenn man jedoch eine Hypothese mit immer neuen “Experimenten” unter immer neuen Rahmenbedingungen “herausfordert” und sie dabei nie falsifiziert wird, dann wird aus einer <strong>einfachen Hypothese</strong> zunehmend <strong>gesichertes Wissen</strong>. Wenn man dagegen eine Hypothese widerlegt hat, muss man zurückgehen. Die vorgeschlagene Erklärung für das gefundene Muster oder sogar das Muster an sich hat sich als nicht korrekt/nicht allgemeingültig herausgestellt. Man muss sich also einen anderen Mechanismus/eine andere Hypothese ausdenken und diese erneut testen. Dies geschieht dann nicht in derselben, sondern in einer folgenden wissenschaftlichen Arbeit.</p>
<p>Mit diesem Wissen über den Ablauf von wissenschaftlicher Erkenntnis und der Rolle des Hypothesentestens dabei habe ich noch eine Frage, zu der ihr euch bis zum Kurstag Gedanken machen solltet:</p>
<section id="frage" class="level5">
<h5 class="anchored" data-anchor-id="frage">Frage</h5>
<p>Profitiert Wissenschaft mehr von der Bestätigung oder von der Falsifizierung von Hypothesen? (Bitte begründet eure Antwort!)</p>
</section>
</section>
</section>
<section id="die-rolle-der-statistik-beim-hypothesengenerieren-und--testen" class="level2">
<h2 class="anchored" data-anchor-id="die-rolle-der-statistik-beim-hypothesengenerieren-und--testen">Die Rolle der Statistik beim Hypothesengenerieren und -testen</h2>
<p>Wir haben gesehen, dass Hypothesen zentral für die moderne Wissenschaft sind, sowohl ihr Generieren als auch ihr Test. Doch welche Rolle spielt die Statistik dabei?</p>
<p>Statistische Verfahren, die implizit oder explizit Hypothesen testen, bezeichnet man als <strong>Inferenzstatistik (schliessende Statistik)</strong> – im Gegensatz zur <strong>deskriptiven Statistik</strong>.</p>
<section id="von-der-hypothese-zur-nullhypothese" class="level4">
<h4 class="anchored" data-anchor-id="von-der-hypothese-zur-nullhypothese">Von der Hypothese zur Nullhypothese…</h4>
<p>Die Herausforderung ist nun aber, wie oben gesehen, dass man eine <strong>Hypothese (H<sup>a</sup> )</strong> (auch <strong>Forschungshypothese</strong> oder <em>a</em><strong>lternative Hypothese</strong> genannt) nicht verifizieren kann, sondern nur falsifizieren. In der Statistik behilft man sich daher mit einem Trick, der sogenannten <strong>Nullhypothese (H<sup>0</sup> )</strong>. Die Nullhypothese ist die Negation der Hypothese, d.&nbsp;h. die Summe aller möglichen Beobachtungen, die mit der Hypothese nicht im Einklang sind. Wenn man nun die Nullhypothese falsifiziert, kann man indirekt die Hypothese bestätigen.</p>
<p>In unserem Beispiel von oben:</p>
<ul>
<li>Hypothese <span class="math inline">\((H_{\Delta})\)</span> : Sorte A und Sorte B unterscheiden sich in ihrer Blütengrösse</li>
<li>Nullhypothese ( <span class="math inline">\(H_{A0}\)</span> ): Sorte A und Sorte B haben die gleiche Blütengrösse</li>
</ul>
<p>Das ist formal korrekt, wissenschaftlich ist die Forschungshypothese aber wenig überzeugend, weil schwerlich ein Mechanismus vorstellbar ist, der in Sorte B sowohl kleinere als auch grössere, nur keine gleich grossen Blüten hervorbringt. Insofern wäre das folgende Paar sinnvoller:</p>
<ul>
<li>Hypothese (H<sub>R</sub>): Sorte A hat grössere Blüten als Sorte B</li>
<li>Nullhypothese ( <span class="math inline">\(H_{B0}\)</span> ): Sorte A hat kleinere oder gleich grosse Blüten wie Sorte B</li>
</ul>
<p>Die erste Forschungshypothese ( <span class="math inline">\(H_A\)</span> ) ist eine ungerichtete Hypothese und entspricht dem, was man in hypothesengenerierender Forschung implizit macht (wenn man also offene Fragen, aber keine konkreten Hypothesen hat). In diesem Fall wäre die zugehörige Forschungsfrage: “Unterscheiden sich die Sorten A und B in ihren Blütengrössen?”. Die zweite Forschungshypothese ( <span class="math inline">\(H_B\)</span> ) ist dagegen gerichtet und wäre für hypothesentestenden Forschung adäquat. In der hypothesentestenden Forschung sollten wir auch eine Begründung/einen Mechanismus anführen, der vermutlich zu dem vorhergesagten Ergebnis führt, etwa dass die Sorte A polyploid ist. Dies gehört zur Begründung der Forschungshypothese, aber ist nicht Bestandteil der Forschungshypothese.</p>
</section>
<section id="einschub-wichtige-termini-in-der-statistik" class="level4">
<h4 class="anchored" data-anchor-id="einschub-wichtige-termini-in-der-statistik">Einschub: Wichtige Termini in der Statistik</h4>
<p>Bis hierher sind uns schon einige wichtige statistische Begriffe (wie Stichprobe und Grundgesamtheit) begegnet, deshalb sollen sie hier samt ihren englischen Pendants noch einmal rekapituliert werden:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 49%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Deutscher Begriff</th>
<th>Englischer<br>Begriff</th>
<th>Definition</th>
<th>Beispiel(e)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Beobachtung</td>
<td>Observation</td>
<td>experimentelle bzw.<br>Beobachtungseinheit</td>
<td>Pflanzenindividuum</td>
</tr>
<tr class="even">
<td>Stichprobe</td>
<td>Sample</td>
<td>alle beprobten Einheiten</td>
<td>die 20 untersuchten<br>Pflanzenindividuen</td>
</tr>
<tr class="odd">
<td>Grundgesamtheit</td>
<td>Population</td>
<td>Gesamtheit aller Einheiten, über<br>die eine Aussage getroffen<br>werden soll</td>
<td>alle Individuen der<br>beiden Sorten</td>
</tr>
<tr class="even">
<td>Messung</td>
<td>Measurement</td>
<td>einzelne erhobene Information</td>
<td>Blütengrösse eines<br>Individuums</td>
</tr>
<tr class="odd">
<td>Variable</td>
<td>Variable</td>
<td>Kategorie der erhobenen<br>Information</td>
<td>Blütengrösse, Sorte</td>
</tr>
</tbody>
</table>
<p>Der englische Begriff <em>population</em> führt oft zu Verwirrung, da er in der Statistik etwas anderes meint als in der Biologie. <em>Population</em> ist schlicht die Grundgesamtheit, die in seltenen Fällen einer biologischen Population entspricht, in den meisten Fällen aber nicht (etwa <em>population of chairs</em>). Auch Messung/<em>measurement</em> wird in der Statistik weiter als in der Allgemeinsprache verwendet, d.&nbsp;h. auch für Zählungen oder Erhebung von kategorialen Variablen.</p>
</section>
<section id="einschub-parameter-vs.-prüfgrössen" class="level4">
<h4 class="anchored" data-anchor-id="einschub-parameter-vs.-prüfgrössen">Einschub: Parameter vs.&nbsp;Prüfgrössen</h4>
<p>Wenn wir in Inferenzstatistik betreiben, also von einer Stichprobe auf die Grundgesamtheit schliessen wollen, müssen wir zudem zwischen Parametern und Prüfgrössen unterscheiden. Unter Parameter (<em>parameter</em>) wird eine Grösse der deskriptiven Statistik für eine bestimmte Variable in der Grundgesamtheit verstanden, über die wir eine Aussage treffen wollen, die wir aber nicht kennen. Dagegen ist eine Prüfgrösse (<em>statistic</em>) eine aus den Messungen der Variablen in der Stichprobe berechnete Grösse, die zur Schätzung des Parameters dient. Etwas verwirrend ist, dass <em>statistic</em> (Prüfgrösse) und <em>statistics</em> (die Statistik als Fach) fast gleich lauten. Oft wird die Konvention verwendet, dass die Prüfgrössen mit kursiven lateinischen Buchstaben (z. B. ) und die korrespondierenden Parameter mit den äquivalenten griechischen Buchstaben (z. B. ) bezeichnet werden (siehe <a href="#page-17-1">Abbildung 1.2</a>).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 8%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Statistic</th>
<th>Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean (µ)</td>
<td><span class="math inline">\(\bar{y}\)</span></td>
<td><span class="math inline">\(\frac{\sum_{i=1}^{n} y_i}{n}\)</span></td>
</tr>
<tr class="even">
<td>Median</td>
<td>Sample median</td>
<td><span class="math inline">\(y_{(n+1)/2}\)</span> if <span class="math inline">\(n\)</span> odd</td>
</tr>
<tr class="odd">
<td>Variance <span class="math inline">\((\sigma^2)\)</span></td>
<td>s <sup>2</sup></td>
<td><span class="math inline">\((y_{n/2} + y_{(n/2)+1})/2\)</span> if <span class="math inline">\(n\)</span> even <span class="math inline">\(\sum_{i=1}^{n} \frac{(y_i - \bar{y})^2}{n-1}\)</span></td>
</tr>
<tr class="even">
<td>Standard deviation <span class="math inline">\((\sigma)\)</span></td>
<td>S</td>
<td><span class="math inline">\(\sqrt{\sum_{i=1}^{n} \frac{(y_i - \bar{y})^2}{n-1}}\)</span></td>
</tr>
<tr class="odd">
<td>Median absolute deviation (MAD)</td>
<td>Sample MAD</td>
<td><span class="math inline">\(median[ y_i - median ]\)</span></td>
</tr>
<tr class="even">
<td>Coefficient of variation (CV)</td>
<td>Sample CV</td>
<td><span class="math inline">\(\frac{s}{\bar{y}} \times 100\)</span></td>
</tr>
<tr class="odd">
<td>Standard error of <span class="math inline">\(\bar{y}\)</span> <span class="math inline">\((\sigma_{\bar{y}})\)</span></td>
<td><span class="math inline">\(S_{\bar{y}}\)</span></td>
<td><span class="math inline">\(\frac{s}{\sqrt{n}}\)</span></td>
</tr>
<tr class="even">
<td>95% confidence interval for <span class="math inline">\(\mu\)</span></td>
<td></td>
<td><span class="math inline">\(\bar{y} - t_{0.05(n-1)} \frac{s}{\sqrt{n}} \le \mu \le \bar{y} + t_{0.05(n-1)} \frac{s}{\sqrt{n}}\)</span></td>
</tr>
</tbody>
</table>
<p>Abbildung 1.2</p>
</section>
</section>
<section id="statistische-implementierung-des-hypothesentestens-am-beispiel-des-t-tests" class="level2">
<h2 class="anchored" data-anchor-id="statistische-implementierung-des-hypothesentestens-am-beispiel-des-t-tests">Statistische Implementierung des Hypothesentestens (am Beispiel des <em>t</em>-Tests)</h2>
<p>Wie lässt sich das Hypothesentesten nun mathematisch und statistisch umsetzen. Wir bleiben bei unserer offenen Forschungsfrage “Unterscheiden sich die Sorten A und B in ihren Blütengrössen?”, woraus sich die Forschungshypothese “Sorten A und B unterscheiden sich in ihren Blütengrössen” ergibt. Mit dem Mittelwert <span class="math inline">\(\mu\)</span> der Variablen (Blütengrösse) in den jeweiligen Grundgesamtheiten (A und B) lassen sich Forschungshypothese und Nullhypothese mathematisch wie folgt formulieren:</p>
<ul>
<li><span class="math inline">\(\text{H}_a\)</span>: <span class="math inline">\(\mu_A \neq \mu_B\)</span></li>
<li><span class="math inline">\(\text{H}_0\)</span>: <span class="math inline">\(\mu_A = \mu_B\)</span> oder <span class="math inline">\(\mu_A - \mu_B = 0\)</span></li>
</ul>
<p>Für die Überprüfung der H<sub>0</sub> gibt es eine Teststatistik (Prüfgrösse) den <em>t</em>-Wert, der wie folgt definiert ist:</p>
<p><span class="math display">\[
t = \frac{\left( {\overline{y}}_{A} - {\overline{y}}_{B} \right) - (\mu_{A} - \mu_{B})}{s_{{\overline{y}}_{A} - {\overline{y}}_{B}}}
\]</span></p>
<p>Da für die <span class="math inline">\(H_0\)</span> gilt <span class="math inline">\(\mu_A - \mu_B = 0\)</span>, lässt sich das vereinfachen zu:</p>
<p><span class="math display">\[
t = \frac{\left( {\overline{y}}_{A} - {\overline{y}}_{B} \right)}{s_{{\overline{y}}_{A} - {\overline{y}}_{B}}}
\]</span></p>
<p>Die Prüfgrösse t ist also die Differenz der beiden Mittelwerte dividiert durch den Standardfehler der Differenz der beiden Mittelwerte. Wenn also die Differenz der Mittelwerte gross und/oder der Standardfehler dieser Differenz klein ist, so ist t weit von Null entfernt.</p>
<p>Was sagt uns der berechnete <em>t</em>-Wert nun? Um daraus etwas schlussfolgern zu können, müssen wir ihn mit der theoretischen <em>t</em>-Verteilung vergleichen. Für diese gilt:</p>
<ul>
<li>Sie ist symmetrisch, mit einem Maximum bei 0.</li>
<li>Der genaue Kurvenverlauf variiert in Abhängigkeit von den Freiheitsgraden (<em>degrees of freedom</em> = df). Bei vielen Freiheitsgraden, d.&nbsp;h. einer grossen Stichprobengrösse (mehr dazu, wie sich die Stichprobenzahl in Freiheitsgrade übersetzt, folgt später), nähert sicht die <em>t</em>-Verteilung einer Normalverteilung (auch <em>z</em>-Verteilung genannt).</li>
</ul>
<p>Die allgemeine Konvention in der Statistik ist, dass die Nullhypothese dann verworfen wird, wenn die berechnete Prüfgrösse extremer ist als 95 % aller möglichen Werte bei der gegebenen Stichprobengrösse. Beim t-Test fragt man also, ob der berechnete t-Wert extremer ist als 95 % aller t-Werte der der Stichprobengrösse entsprechenden t-Verteilung. Da unsere Hypothese ungerichtet ist (also ist verschieden und nicht ist grösser/ist kleiner), benötigen wir einen zweiseitigen t-Test. Dieser bestimmt die “kritischen” t-Werte ( <span class="math inline">\(t_c\)</span> ), indem auf beiden Seiten quasi 2.5 % der Fläche des Integrals unter der Wahrscheinlichkeitsverteilung abgeschnitten werden, wie die folgende Abbildung visualisiert:</p>
<p><img src="Statistik_Skript _v.41_SW/_page_18_Figure_4.jpeg" class="img-fluid"></p>
<p>Wenn also der berechnete t-Wert &gt; <span class="math inline">\(t_c\)</span> (oder &lt; <span class="math inline">\(-t_c\)</span> ) ist, dann sind wir <strong>hinreichend sicher</strong>, dass sich die Mittelwerte nicht nur in der Stichprobe, sondern auch in der Grundgesamtheit unterscheiden.</p>
<section id="fehler-i.-und-ii.-art" class="level4">
<h4 class="anchored" data-anchor-id="fehler-i.-und-ii.-art">Fehler I. und II. Art</h4>
<p>Wichtig ist, dass es in der physischen Realität nie eine absolute Sicherheit gibt. Wenn wir also wir feststellen, dass die Wahrscheinlichkeit, dass die Nullhypothese zutrifft (oder präziser: dass das vorliegende Ergebnis oder ein extremeres bei Zutreffen der Nullhypothese aufgetreten wäre) kleiner als 5 % ist, gibt es eben doch Fälle gibt, in denen wir fälschlich die Nullhypothese verwerfen, d.&nbsp;h. das Vorliegend eines Effektes bejahen, obwohl er in der Realität (d.&nbsp;h. der Grundgesamtheit) nicht auftritt. Das bezeichnet man als <strong>Typ I-Fehler</strong>. Umgekehrt kann es aber auch passieren, dass man die Nullhypothese aufgrund des statistischen Tests beibehält, also einen Effekt nicht nachweist, obwohl er in der Realität existiert (<strong>Typ II-Fehler</strong>). Diese beiden Phänomene sind in der folgenden beiden Abbildungen visualisiert:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 11%">
<col style="width: 28%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th></th>
<th>Statistische Schlussfolgerung</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td>H<sub>0</sub> wird verworfen</td>
<td>H<sub>0</sub> wird beibehalten</td>
</tr>
<tr class="even">
<td>Situation in der Realität<br>(d.h. der Grundgesamtheit)</td>
<td>Effekt existiert</td>
<td>Korrekte Entscheidung:<br>Effekt vorhanden und<br>nachgewiesen</td>
<td>Typ II-Fehler:<br>Effekt nicht nachgewiesen,<br>obwohl vorhanden</td>
</tr>
<tr class="odd">
<td>Situation in der Realität<br>(d.h. der Grundgesamtheit)</td>
<td>Effekt existiert<br>nicht</td>
<td>Typ I-Fehler:<br>Effekt nachgewiesen, aber<br>nicht vorhanden</td>
<td>Korrekte Entscheidung:<br>Effekt nicht vorhanden und<br>auch nicht nachgewiesen</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/errors.png" class="img-fluid figure-img"></p>
<figcaption>(aus Quinn &amp; Keough 2002)</figcaption>
</figure>
</div>
<p>Wie man der zweiten Visualisierung entnehmen kann, steigt die Wahrscheinlichkeit eines Typ II-Fehlers, je weiter man die akzeptierte Wahrscheinlichkeit eines Typ I-Fehlers reduziert. In der Statistik wir im Allgemeinen sehr viel stärker auf die Minimierung von Typ I-Fehlern fokussiert, d.&nbsp;h. man will vermeiden, dass man fälschlich einen Effekt behauptet, der in Realität nicht existiert, während es als weniger problematisch angesehen wird, einen vorhandenen, aber dann sehr schwachen Effekt, nicht nachgewiesen zu haben.</p>
</section>
<section id="p-werte-und-signifikanzniveaus" class="level4">
<h4 class="anchored" data-anchor-id="p-werte-und-signifikanzniveaus"><em>p</em>-Werte und Signifikanzniveaus</h4>
<p>Signifikanzniveaus und p-Werte sind zentrale Termini in der am weitesten verbreiteten inferenzstatistischen Schule, der <em>frequentist statistics</em> (“Frequentistische Statistik”, aber ich habe den Begriff noch nie im Deutschen gehört). Deren Grundideen sind:</p>
<ul>
<li>Die beobachteten Werte werden als eine Beobachtung unter vielen möglichen Beobachtungen interpretiert, die zusammen eine <strong>Häufigkeitsverteilung</strong> ergeben.</li>
<li>Es wird eine <strong>einzige wahre Beschreibung der Realität</strong> angenommen, der man sich mit bestimmten Irrtumswahrscheinlichkeiten annähern kann.</li>
</ul>
<p>In der <em>frequentist statistics</em>, sind die <em>p</em>-Werte das zentrale “Gütemass”. Als <em>p</em><strong>-Wert</strong> bezeichnet man dabei die berechnete <strong>Wahrscheinlichkeit eines Typ I-Fehlers</strong>. Der <em>p</em>-Wert bezeichnet also die Wahrscheinlichkeit, dass man aufgrund des statistischen Tests einen Zusammenhang feststellt, ohne dass dieser in Realität existiert.</p>
<p>Als <strong>statistisch signifikant</strong> bezeichnet man Ergebnisse, die unter einem bestimmten <em>p</em>-Wert liegen. Diese Schwellenwerte sind Konventionen und nicht “gottgegeben”. Traditionell werden drei Signifikanzniveaus verwendet (wozu R noch ein viertes hinzugefügt hat, das man mit “marginal signifikant” bezeichnen könnte), die wie folgt notiert werden:</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>***</td>
<td>p &lt; 0.001</td>
<td>höchst signifikant; highly significant</td>
</tr>
<tr class="even">
<td>**</td>
<td>p &lt; 0.01</td>
<td>hoch signifikant; very significant</td>
</tr>
<tr class="odd">
<td>*</td>
<td>p &lt; 0.05</td>
<td>signifikant; significant</td>
</tr>
<tr class="even">
<td></td>
<td>p &lt; 0.1</td>
<td>marginal signifikant; marginally significant</td>
</tr>
</tbody>
</table>
<p>Die Schwellenwerte der Signifikanzniveaus (d.&nbsp;h. Schwellenwerte für akzeptierte Typ I-Fehler) werden auch mit α bezeichnet. Was man in einer Arbeit als signifikant betrachtet, sollte man vor Beginn der Untersuchung festlegen und im Methodenteil schreiben (“als Signifikanzschwelle verwenden wir” oder “als signifikant sehen wir Ergebnisse mit an”). Es bietet sich normalerweise an, bei der allgemeinen Konvention von zu bleiben, es sei denn es sprechen spezifische Gründe dagegen. Ein Grund könnte sein, dass die Verwerfung der Nullhypothese/Annahme der Forschunshypothese schwerwiegende Folgen hätte und man sich daher besonders sicher sein will.</p>
<p>Da sich ober- und unterhalb der genannten Schwellen nichts Fundamentales ändert, sollte man grundsätzlich die exakten <em>p</em>-Werte mit drei Nachkommastellen (z. B. “” bzw. wenn noch niedriger als ““) angeben. Zur besseren Lesbarkeit können zusätzlich die korrespondierenden Signifikanzniveaus angegeben werden.</p>
<p>Es ist wichtig, sich bewusst zu sein, dass <strong>statistisch signifikant nicht gleichbedeutend ist mit biologisch bzw. sozialwissenschaftlich bedeutsam</strong>. Ein Effekt kann statistisch hoch signifikant sein (wg. grosser Stichprobengrösse) und trotzdem inhaltlich bedeutungslos (da die Effektgrösse minimal ist). Umgekehrt kann ein inhaltlich bedeutsamer Effekt evtl. nicht statistisch signifikant nachgewiesen werden, wenn man extrem wenige Replikate hatte.</p>
<p>Mit dem Kriterium “statistische Signifikanz”/<em>p</em>-Wert trennen wir unsere Ergebnisse in einem ersten Schritt in jene, die wir für <strong>belastbar</strong> halten und jene, die mit grosser Wahrscheinlichkeit “zufällig” (“Rauschen in den Daten”, Messungenauigkeit, etc.) zustande gekommen sind. Bei den belastbaren müssen wir dann immer noch ihre <strong>Relevanz</strong> (also die Effektstärke) beurteilen.</p>
</section>
</section>
<section id="t-test-für-eine-metrische-variable-im-vergleich-von-zwei-gruppen" class="level2">
<h2 class="anchored" data-anchor-id="t-test-für-eine-metrische-variable-im-vergleich-von-zwei-gruppen"><em>t</em>-Test (für eine metrische Variable im Vergleich von zwei Gruppen)</h2>
<p>Der <em>t</em>-Test ist eines der einfachsten inferenzstatistischen Verfahren. Er vergleicht zwei Gruppen statistisch, wenn die abhängige Variable metrisch ist.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Sorte Andro</th>
<th>Sorte Bullie</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>20</td>
<td>12</td>
</tr>
<tr class="even">
<td>19</td>
<td>15</td>
</tr>
<tr class="odd">
<td>25</td>
<td>16</td>
</tr>
<tr class="even">
<td>10</td>
<td>7</td>
</tr>
<tr class="odd">
<td>8</td>
<td>8</td>
</tr>
<tr class="even">
<td>15</td>
<td>10</td>
</tr>
<tr class="odd">
<td>13</td>
<td>12</td>
</tr>
<tr class="even">
<td>28</td>
<td>11</td>
</tr>
<tr class="odd">
<td>11</td>
<td>13</td>
</tr>
<tr class="even">
<td>14</td>
<td>10</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(H_0\)</span> : Die beiden Sorten unterscheiden sich nicht in der Blütengrösse.</p>
<section id="students-und-welch-t-test" class="level5">
<h5 class="anchored" data-anchor-id="students-und-welch-t-test">Students und Welch t-Test</h5>
<p>Als statistisches Verfahren kommt <strong>Students</strong> <em>t</em>-<strong>Test für zwei unabhängige Stichproben</strong> zum Einsatz (“Student” ist das Pseudonym für William Sealy Gosset, dem Erfinder des Tests, dessen Arbeitsvertrag in der Privatwirtschaft das Publizieren von Ergebnissen verbot).</p>
<p><span class="math display">\[
t = \frac{\bar{X}_1-\bar{X}_2}{s_p\times \sqrt{\frac{1}{n_1}+\frac{1}{n_2}}}
\]</span></p>
<p>Wobei <span class="math inline">\(s_p\)</span> der gepoolten Varianz entspricht:</p>
<p><span class="math display">\[
s_p = \sqrt{\frac{(n_1-1)s^{2}_{X_{1}}+(n_2-1)s^{2}_{X_{2}}))}{n_1+n_2-2}}
\]</span></p>
<p>Der berechnete t-Wert wird mit der t-Verteilung für <span class="math inline">\((n_1 - 1) + (n_2 - 1)\)</span> Freiheitsgraden verglichen. Der klassische t-Test setzt Normalverteilung und gleiche Varianzen voraus:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(size <span class="sc">~</span> cultivar, <span class="at">var.equal =</span> T, <span class="at">data =</span> blume)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<p>Wenn Varianzgleichheit nicht gegeben ist, verwendet man Welch’ <em>t</em>-Test. Dieser approximiert die Freiheitsgrade mit der Welch-Satterthwaite-Gleichung. Er setzt weiterhin Normalverteilung voraus, benötigt aber keine gleichen Varianzen. Welch’ <em>t</em>-Test kann/sollte also immer verwendet werden, wenn keine vorherigen Tests auf Varianzgleichheit durchgeführt werden und ist daher Standard (default) in R:</p>
<p><span class="math display">\[
t = \frac{\bar{X}_1 - \bar{X}_2}{s\frac{}{\Delta}}
\]</span></p>
<p>Wobei</p>
<p><span class="math display">\[
s\frac{}{\Delta} = \sqrt{\frac{s^2_1}{n_1}+\frac{s^2_2}{n_2}}
\]</span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(size <span class="sc">~</span> cultivar, <span class="at">var.equal =</span> <span class="cn">FALSE</span>, <span class="at">data =</span> blume)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(size <span class="sc">~</span> cultivar, <span class="at">data =</span> blume)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="ein--und-zweiseitiger-t-test" class="level4">
<h4 class="anchored" data-anchor-id="ein--und-zweiseitiger-t-test">Ein- und zweiseitiger t-Test</h4>
<p>Bislang war unsere Hypothese, dass irgendein Unterschied vorliegt (was, wie oben dargelegt, keine adäquate Forschungshypothese ist, sondern die implizite Hypothese, wenn man eine offene Frage formuliert, aber keine klare Theorie hat). Wenn es eine Theorie gibt, aus der sich eine klare Vorhersage treffen lässt, so enthält diese normalerweise auch eine Aussage über die Richtung des Effekts, also ob die Blüten von Andro grösser als jene von Bulliesind oder umgekehrt. Dann verwendet man einen einseitigen t-Test, denn man je nach Richtung der Hypothese mit greater oder less spezifizieren muss. Bildlich gesprochen werden beim gängigen Signifikanzniveau von <span class="math inline">\(\alpha = 0.05\)</span> beim beidseitigen t-Test je 2.5 % der Integralfläche links und rechts “abgeschnitten”, beim einseitigen t-Test dagegen 5 % auf einer Seite. Wenn der berechnete t-Wert in einem der abgeschnittenen “Dreiecke” liegt, ist das Ergebnis signifikant.</p>
<p><img src="Statistik_Skript _v.41_SW/_page_23_Figure_0.jpeg" class="img-fluid"></p>
<p><img src="Statistik_Skript _v.41_SW/_page_23_Figure_1.jpeg" class="img-fluid"></p>
<p>(aus Quinn &amp; Keough 2002)</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(size <span class="sc">~</span> cultivar, <span class="at">data =</span> blume) <span class="co"># zweiseitig</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(size <span class="sc">~</span> cultivar, <span class="at">alternative =</span> <span class="st">"greater"</span>, <span class="at">data =</span> blume ) <span class="co"># einseitig</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(size <span class="sc">~</span> cultivar, <span class="at">alternative =</span> <span class="st">"less"</span>, <span class="at">data =</span> blume) <span class="co"># einseitig</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="gepaarter-und-ungepaarter-t-test" class="level4">
<h4 class="anchored" data-anchor-id="gepaarter-und-ungepaarter-t-test">Gepaarter und ungepaarter <em>t</em>-Test</h4>
<p>Bislang haben wir angenommen, dass die Individuen der beiden Sorten unabhängig voneinander jeweils zufällig ausgewählt wurden. Dann ist ein ungepaarter <em>t</em>-Test (<em>default</em>-Einstellung in R) richtig. Wenn jedoch je zwei Messwerte zusammengehören, etwa wenn je eine Pflanze der Sorten Andro und Bullie gemeinsam in einem Topf wuchs, so kommt ein gepaarter <em>t</em>-Test zur Anwendung. Da dieser mehr “Informationen” zur Verfügung hat, hat er mehr statistische “<em>power</em>”, wird i. d.&nbsp;R. also zu stärker signifikanten Ergebnissen führen:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(blume<span class="sc">$</span>size[blume<span class="sc">$</span>cultivar <span class="sc">==</span> <span class="st">"Andro"</span>], blume<span class="sc">$</span>size[blume<span class="sc">$</span>cultivar <span class="sc">==</span> <span class="st">"Bullie"</span>], <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="binomial-test-für-die-häufigkeitsverteilung-einer-binomialen-variablen" class="level2">
<h2 class="anchored" data-anchor-id="binomial-test-für-die-häufigkeitsverteilung-einer-binomialen-variablen">Binomial-Test (für die Häufigkeitsverteilung einer binomialen Variablen)</h2>
<p>Der Binomial-Test testet, ob die Verteilung einer binären Variable von einer Zufallsverteilung abweicht. Eine binomiale (binäre) Variable ist eine, die zwei mögliche Zustände hat, etwa lebend/tot, männlich/weiblich oder besser/schlechter. Wenn das Ergebnis zufällig wäre, müssten in der Stichprobe beide Ausprägungen ungefähr gleich häufig vertreten sein. Folglich testet der Binomialtest, wie wahrscheinlich es ist, dass die vorgefundene Häufigkeitsverteilung in der Stichprobe zustande gekommen wäre, wenn beide Zustände gleich häufig sind. Wenn diese Wahrscheinlichkeit &lt; 0.05 ist, nimmt man in der Statistik gewöhnlich an, dass der Unterschied in der Stichprobe einem realen Unterschied in der Grundgesamtheit ist.</p>
<p>Betrachten wir den Frauenanteil im schweizerischen Nationalrat als Beispiel. Im Jahr 2019 waren 84 von 200 Mitgliedern weiblich (42%). Nehmen wir in guter Näherung an, dass im Stimmvolk das Geschlechterverhältnis 1:1 ist: Kann die Abweichung von 50 % unter den Mitgliedern noch durch Zufall erklärt werden oder deutet das auf eine “Bevorzugung” von Männern bei der Kandidat:innenaufstellung und im Wahlvorgang hin. Die Antwort liefert der Binomialtest, dem man die Zahl der “Erfolge” (weiblich: 84) und die Stichprobengrösse (200) übergeben muss:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="dv">84</span>, <span class="dv">200</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>Exact binomial test</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>data:  84 and 200</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>number of successes = 84, number of trials = 200, p-value = 0.02813</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>alternative hypothesis: true probability of success is not equal to 0.5</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>95 percent confidence interval:</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a> 0.3507439 0.4916638</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>sample estimates:</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>probability of success</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>                  0.42</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<p>Der Unterschied ist also signifikant (<em>p</em> &lt; 0.05), wir können die Nullhypothese (“keine Bevorzugung von Männern”) also verwerfen. Der Output sagt uns auch noch, dass ohne Bevorzugung / Benachteiligung eines Geschlechts der gegenwärtige Frauenanteil im Nationalrat nur zustande hätte kommen können, wenn der Frauenanteil im Stimmvolk zwischen 35 % und 49 % läge. Da dieser Bereich 50 % (also den der Nullhypothese entsprechenden Wert) nicht einschliesst, ist es logisch, dass diese verworfen wird. Der Test ist “symmetrisch”: Wir können also statt der Anzahl der weiblichen Nationalratsmitglieder auch jene der männlichen eingeben und bekommen den gleichen <em>p</em>-Wert</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="dv">116</span>, <span class="dv">200</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>Exact binomial test</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>data:  116 and 200</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>number of successes = 116, number of trials = 200, p-value = 0.02813</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>alternative hypothesis: true probability of success is not equal to 0.5</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>95 percent confidence interval:</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a> 0.5083362 0.6492561</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>sample estimates:</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>probability of success</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>                  0.58</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<p>Man kann den Binomial-Test auch als <strong>Vorzeichen-Test</strong> (<em>sign test</em>) verwenden. Der Code ist der gleiche, die Bedeutung aber eine etwas andere. Der Vorzeichen-Test wird verwendet, wenn man testen will, ob es eine gerichtete Veränderung einer Zielvariablen über die Zeit gegeben hat. Beispielsweise könnte man fragen, wie sich eine Art in einer Anzahl von Untersuchungsflächen zwischen Zeitpunkt A und Zeitpunkt B in ihrer Häufigkeit verändert hat:</p>
<p>Dann gibt es für jede Untersuchungsfläche vier Möglichkeiten:</p>
<ol type="1">
<li>Die Art kam zum Zeitpunkt A und B vor</li>
<li>Die Art kam weder zum Zeitpunkt A noch zum Zeitpunkt B vor</li>
<li>Die Art kam zum Zeitpunkt A vor, ist aber zum Zeitpunkt B verschwunden</li>
<li>Die Art kam zum Zeitpunkt A nicht vor, trat aber zum Zeitpunkt B neu auf</li>
</ol>
<p>Um den Vorzeichen-Test anzuwenden, ignorieren wir die Fälle 1 und 2 (ohne Veränderung) und berücksichtigen nur die Fälle 3 und 4 (mit Veränderung). Angenommen es gäbe 10 Flächen mit negativer, und 2 mit positiver Entwicklung, dann lautet der R Code folgendermassen (die Grundgesamtheit sind hier die Flächen mit Veränderung, also 10 + 2 =12).</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="dv">10</span>, <span class="dv">12</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># alternative notion binom.test(c(10, 2))</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="möglichkeiten-zwei-stichproben-zu-vergleichen-und-implikationen-für-das-samplingdesign" class="level2">
<h2 class="anchored" data-anchor-id="möglichkeiten-zwei-stichproben-zu-vergleichen-und-implikationen-für-das-samplingdesign">Möglichkeiten, zwei Stichproben zu vergleichen, und Implikationen für das Samplingdesign</h2>
<p>Bislang haben wir verschiedene Verfahren angeschaut, die auf Unterschieden zwischen zwei Stichproben testen. Welcher dieser Tests Verwendung finden kann, hängt (a) von der raumzeitlichen Anordnung der Beobachtungen und (b) von der Residual-Verteilung der abhängigen Variablen ab. Das <strong>Sampling oder Experimentaldesign</strong> muss also immer passend zur geplanten Statistik und die verwendete Statistik passend zum Samplingdesign gewählt werden. Passen Samplingdesign und statistisches Verfahren nicht zusammen, liefert R falsche Ergebnisse, da das Programm ja nicht weiss, wie die Beobachtungen raum-zeitlich angeordnet waren.</p>
<p>Grundsätzlich müssen die Beobachtungen in der Stichprobe so räumlich-zeitlich verteilt werden, dass sie zufällig oder ggf. systematisch in demjenigen Raum verteilt sind, den sie repräsentieren sollen. Erhebungen nur in Zürich zu machen, dann aber eine Aussage für die ganze Schweiz treffen zu wollen, geht also nicht.</p>
<section id="gepaarte-vs.-ungepaart-tests" class="level4">
<h4 class="anchored" data-anchor-id="gepaarte-vs.-ungepaart-tests">Gepaarte vs.&nbsp;ungepaart Tests</h4>
<p>Wir haben den ungepaarten und den gepaarten <em>t</em>-Test kennen gelernt. Gepaart bedeutet im einfachsten Fall, dass an den gleichen Untersuchungsobjekten zu zwei Zeitpunkten eine abhängige Grösse erhoben wurde. Vielfach wird mit gepaarten Tests aber auch bei räumlicher Nähe gearbeitet. In der folgenden Abbildung ist das visualisiert für den Vergleich von zwei Sorten im Gewächshaus (die beiden Farben). Das könnten genauso Individuen einer Art in einem Naturschutzgebiet sein usw. Dargestellt sind vier mögliche Anordnungen (wobei aus statistischer Sicher eine Zufallsverteilung optimal wäre, aber meist eine systematische Verteilung ebenfalls ohne Verzerrungen (<em>bias</em>) angewandt werden kann und vielfach einfacher zu implementieren ist).</p>
<p><img src="Statistik_Skript _v.41_SW/_page_26_Figure_0.jpeg" class="img-fluid"></p>
<p>Mögliche räumliche Verteilung von Objekten in einem Sampling- oder Experimentaldesign. Der schwarze Rahmen könnte das Gewächshaus sein und die roten und blauen Kreise die Töpfe der Versuchspflanzen der beiden Sorten. Die vier Anordnungen sind im Text erklärt.</p>
<p><strong>Anordnung a</strong> ist statistisch korrekt für einen Vergleich der beiden Sorten, aber man macht dann keine Aussage über das ganze Gewächshaus, sondern nur über seine obere rechte Ecke. <strong>Anordnung b</strong> erlaubt dagegen keinen Vergleich zwischen den beiden Sorten, da die roten Töpfe alle links und die blauen Töpfe alle rechts stehen. Wenn man hier einen Unterschied zwischen rot und blau mit dem t-Test gefunden hat, könnte das in Wahrheit auch ein Unterschied zwischen der linken und rechten Seite des Gewächshauses sein. Der <em>t</em>-Test spuckt dann zwar eine <em>p</em>-Wert aus, aber der beantwortet nicht unsere Frage. Man nennt das <strong>Pseudoreplikation</strong>, da R glaubt, es hätte sechs rote und sechs blaue Pflanzen, die unabhängig voneinander sind (<em>n</em> = 12). De facto hat man aber nur ein rotes und ein blaues Cluster (<em>n</em> = 2). <strong>Anordnung c</strong> ist optimal für die Anwendung eines ungepaarten <em>t</em>-Tests (die Töpfe der beiden Sorten sind unabhängig voneinander zufällig im Gewächshaus verteilt). <strong>Anordnung d</strong> schliesslich ist gut für einen gepaarten t-Test, da die sechs Gruppen zufällig (oder hier: systematisch) im Gewächshaus verteilt wurden, und innerhalb jedes Paars die Sorte wiederum zufällig oder in einem Schachbrettmuster den beiden Töpfen zugewiesen wurde.</p>
</section>
<section id="nutzung-des-vorzeichentests-bei-gepaarten-erhebungen" class="level4">
<h4 class="anchored" data-anchor-id="nutzung-des-vorzeichentests-bei-gepaarten-erhebungen">Nutzung des Vorzeichentests bei gepaarten Erhebungen</h4>
<p>Wenn man den Binomial-Test als Vorzeichen-Test verwendet, kann dieser auch gut bei gepaarten Erhebungen (Anordnung d in der Abbildung oben) Anwendung finden. Dies gilt für zwei Fälle: (a) die Residuen sind so ungünstig, dass weder eine Transformation noch der Wilcoxon-Text hilft, (b) es wird eine nicht messbare ordinale Grösse erhoben (z.B. Geschmack von Kulturpflanzen). Das Vorgehen ist dann jeweils so, dass für jedes Paar entschieden wird, ob Sorte A grösser/besser ist also Sorte B oder umgekehrt. Die Paare, bei denen man nicht unterscheiden kann, weil die Messwerte gleich oder die ordinale Grösse zu ähnlich ist, werden vor der Anwendung des Tests ausgeschlossen. Wären beide Sorten hinsichtlich der Zielgrösse gleich, müsste in 50% der Fälle Sorte A grösser/besser sein, und in 50% der Fälle Sorte B. Gibt es eine signifikante Abweichung von 50 zu 50 schliessen wir auf einen Unterschied.</p>
</section>
</section>
<section id="chi-quadrat--bzw.-fishers-test-für-die-assoziation-zweier-binomialer-variablen" class="level2">
<h2 class="anchored" data-anchor-id="chi-quadrat--bzw.-fishers-test-für-die-assoziation-zweier-binomialer-variablen">Chi-Quadrat- bzw. Fishers Test (für die Assoziation zweier binomialer Variablen)</h2>
<p>Die Frage beim Assoziationstest ist eine ähnliche wie beim Binomialtest. Wiederum geht es um binomiale Variablen, dieses Mal aber nicht um eine einzige, sondern um zwei an denselben Objekten erhobene Variablen, deren Zusammenhang man wissen will.</p>
<p>Im folgenden Beispiel wollen wir wissen, ob die Augenfarbe und die Haarfarbe von Personen miteinander zusammenhängen. Die einfachste Form des Assoziationstests setzt zwei binomiale/ binäre Variablen voraus, wir müssen also z. B. grüne Augen ausschliessen oder mit einer der beiden anderen Augenfarben zusammenfassen. Unsere Beobachtungsergebnisse von 114 Personen könnten wie folgt aussehen:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Blaue Augen</th>
<th>Braune Augen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Helle Haare</td>
<td>38</td>
<td>11</td>
</tr>
<tr class="even">
<td>Dunkle Haare</td>
<td>14</td>
<td>51</td>
</tr>
</tbody>
</table>
<p>Sind diese Werte so erwartbar unter der Nullhypothese, dass Augenfarbe und Haarfarbe unabhängig voneinander sind? Anders als beim Binomialtest oben ist die Nullhypothese jedoch nicht die Gleichverteilung aller Merkmale bzw. Merkmalskombinationen. Vielmehr gehen wir von der gegebenen Häufigkeit der vier Einzelmerkmale aus. Wir müssen also berechnen, mit welcher Wahrscheinlichkeit die Kombination blaue Augen – helle Haare unter den 114 Probant:innen auftreten sollte, wenn beide Merkmale unabhängig voneinander sind. Das geht folgendermassen:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 29%">
<col style="width: 29%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Blaue Augen</th>
<th style="text-align: center;">Braune Augen</th>
<th style="text-align: center;"><strong>Zeilen Total </strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Helle Haare</td>
<td style="text-align: center;"><span class="math inline">\(\frac{49\times 52}{114}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{49\times 62}{114}\)</span></td>
<td style="text-align: center;"><strong>49</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Dunkle Haare</td>
<td style="text-align: center;"><span class="math inline">\(\frac{65\times 52}{114}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{65\times 62}{114}\)</span></td>
<td style="text-align: center;"><strong>65</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Reihen Total</strong></td>
<td style="text-align: center;"><strong>52</strong></td>
<td style="text-align: center;"><strong>62</strong></td>
<td style="text-align: center;"><strong>114</strong></td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Blaue Augen</th>
<th style="text-align: center;">Braune Augen</th>
<th style="text-align: center;">Zeilen total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Helle Haare</td>
<td style="text-align: center;">22.35</td>
<td style="text-align: center;">26.65</td>
<td style="text-align: center;"><strong>49</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Dunkle Haare</td>
<td style="text-align: center;">29.65</td>
<td style="text-align: center;">33.35</td>
<td style="text-align: center;"><strong>65</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Reihen Total</strong></td>
<td style="text-align: center;"><strong>52</strong></td>
<td style="text-align: center;"><strong>62</strong></td>
<td style="text-align: center;"><strong>114</strong></td>
</tr>
</tbody>
</table>
<p>Die beobachteten Werte (z. B. 38 Personen mit blauen Augen/hellen Haare) unterscheiden sich deutlich von den erwarteten Werten unter der Nullhypothese (22.35 Personen). Aber ist das auch statistisch signifikant?</p>
<section id="chi-quadrat-test" class="level4">
<h4 class="anchored" data-anchor-id="chi-quadrat-test">Chi-Quadrat-Test</h4>
<p>Der traditionelle statistische Test für diese Frage ist Pearsons Chi-Quadrat-Test (auch <span class="math inline">\(X^2\)</span> -Test geschrieben). Wie t ist <span class="math inline">\(X^2\)</span> eine Teststatistik, die abhängig von den Freiheitsgraden (df) einer ganz bestimmten Kurve folgt.</p>
<p><span class="math display">\[
X^2= \sum{\frac{(O-E)^2}{E}}
\]</span></p>
<p>Wobei <span class="math inline">\(O = \text{observed}\)</span>, <span class="math inline">\(E = \text{expected}\)</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Statistik_Skript _v.41_SW/_page_29_Picture_0.jpeg" class="img-fluid figure-img"></p>
<figcaption>(aus Quinn &amp; Keough 2002)</figcaption>
</figure>
</div>
<p>Wir können den <span class="math inline">\(\chi^2\)</span> -Wert in unserem Fall einfach händisch berechnen:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 13%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">O</th>
<th style="text-align: center;">E</th>
<th style="text-align: center;"><span class="math inline">\((O-E)^2\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\frac{(O-E)^2}{E}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Helle Haare &amp; blaue Augen</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">22.35</td>
<td style="text-align: center;">244.92</td>
<td style="text-align: center;">10.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">Helle Haare &amp; braune Augen</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">26.65</td>
<td style="text-align: center;">244.92</td>
<td style="text-align: center;">9.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dunkle Haare &amp; blaue Augen</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">29.65</td>
<td style="text-align: center;">244.92</td>
<td style="text-align: center;">8.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dunkle Haare &amp; braune Augen</td>
<td style="text-align: center;">51</td>
<td style="text-align: center;">35.35</td>
<td style="text-align: center;">244.92</td>
<td style="text-align: center;">6.93</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X<sub>2</sub></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">35.33</td>
</tr>
</tbody>
</table>
<p>Ist <span class="math inline">\(\chi^2 = 35.33\)</span> nun signifikant oder nicht? Dazu müssen wir noch die Freiheitsgrade berechnen und das Signifikanzniveau festlegen:</p>
<ul>
<li><strong>Freiheitsgrade:</strong> <span class="math inline">\((\text{Spalten}-1)\times(\text{Zeilen}-1)=(2-1)\times(2-1)=1\)</span></li>
<li><strong>Signifikanzlevel:</strong> z. B. <span class="math inline">\(\alpha = 0.05\)</span></li>
</ul>
<p>Traditionell hätte man den kritischen Wert für diese Kombination in einer gedruckten Tabelle nachgeschlagen. Wir fragen einfach R, wobei wir 1 – α (in unserem Fall 1-0.05) eingeben müssen, da wir wissen wollen, ob wir im äussersten rechten Teil der Verteilungskurve liegen, also extremer als 95 % der Werte unter der Nullhypothese keiner Assoziation.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>, <span class="dv">1</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>[1] 3.841495</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<p>Unser berechneter <em>Χ</em>²-Wert (35.33) ist viel grösser als der kritische Wert (3.84), also gibt es eine Assoziation zwischen den Variablen (d.&nbsp;h. die Kombinationen blau/hell und braun/dunkel sind überproportional häufig). Wenn wir, wie oben empfohlen, einen präzisen p-Wert für die Assoziation wollen, erhalten wir ihn folgendermassen (beachte, dass chisq.test eine Matrix oder ein data frame als Argument benötigt):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>count <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">38</span>, <span class="dv">14</span>, <span class="dv">11</span>, <span class="dv">51</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(count)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>Pearson's Chi-squared test with Yates' continuity correction</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>data:  count</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>X-squared = 33.112, df = 1, p-value = 8.7e-09</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<p>Der ausgegebene <em>Χ</em>²-Wert (33.11) ist etwas niedriger als der oben händisch berechnete (35.33), da R noch die Yates-Korrektur anwendet, um zu kompensieren, dass wir es hier mit Ganzzahlen (diskreten Werten) zu tun haben, während die <em>Χ</em>²-Verteilung kontinuierliche Werte unterstellt. Die Assoziation bleibt aber trotzdem höchst signifikant (<em>p</em> &lt; 0.001).</p>
</section>
<section id="fishers-exakter-test" class="level4">
<h4 class="anchored" data-anchor-id="fishers-exakter-test">Fishers exakter Test</h4>
<p>Für kleine Erwartungswerte in den Zellen (&lt; 5) ist der Chi-Quadrat-Test nicht zuverlässig. Dafür gibt es Fishers exakten Test.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>count2 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">9</span>, <span class="dv">1</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(count2)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>Fisher's Exact Test for Count Data</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>data:  count</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>p-value = 0.04299</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>alternative hypothesis: true odds ratio is not equal to 1</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>95 percent confidence interval:</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a> 0.001280876 1.102291244</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>sample estimates:</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>odds ratio</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a> 0.08026151</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<p>Man kann/sollte Fishers exakten Test jedoch grundsätzlich verwenden, da er mit der heutigen Rechenleistung von Computern kein Problem mehr darstellt. Angewandt auf unseren Haarfarben / Augenfarben-Datensatz ergibt sich:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(count)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>Fisher's Exact Test for Count Data</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>data:  count</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>p-value = 2.099e-09</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>alternative hypothesis: true odds ratio is not equal to 1</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>95 percent confidence interval:</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  4.746351 34.118920</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>sample estimates:</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>odds ratio</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  12.22697</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<p>Wie man der Ausgabe entnehmen kann, ist die Teststatistik hier anstelle von <em>Χ</em>² die sogenannte <em>odds ratio</em>, ein Begriff, für den es keine gute deutsche Übersetzung gibt. Sie bezeichnet die <strong>Wahrscheinlichkeit des Eintretens geteilt durch die Wahrscheinlichkeit des Nichteintretens</strong>. Aus der Umgangssprache und Wettspielen sind wir bereits vertraut mit <em>odds ratios</em>: “50:50-Chancen” bezeichnen nichts anderes als eine <em>odds ratio</em> von 1 (50 / 50 = 1). Bei einem Assoziationstest ist entspricht der <em>odds rati</em>o die Multiplikation der Wahrscheinlichkeiten auf der einen Diagonalen geteilt durch jene der anderen Diagonalen, also (38 x 51) / (14 x 11).</p>
</section>
</section>
<section id="wie-berichtet-man-statistische-ergebnisse" class="level2">
<h2 class="anchored" data-anchor-id="wie-berichtet-man-statistische-ergebnisse">Wie berichtet man statistische Ergebnisse?</h2>
<section id="welche-relevanten-informationen-benötige-ich-und-wo-finde-ich-sie" class="level4">
<h4 class="anchored" data-anchor-id="welche-relevanten-informationen-benötige-ich-und-wo-finde-ich-sie">Welche relevanten Informationen benötige ich und wo finde ich sie?</h4>
<p>Die Ergebnisausgaben in R sind mitunter umfangreich. Da kommt es darauf an, effizient herausfiltern zu können, was welche Information darin bedeutet und welche davon man in einer wissenschaftlichen Arbeit braucht. Hier ist die Ausgabe des vorhergehenden gepaarten <em>t</em>-Tests, und was die jeweiligen Zeilen bedeuten:</p>
<pre><code>    Paired t-test

data:  blume$a and blume$b
t = 3.4821, df = 9, p-value = 0.006916
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 1.366339 6.433661
sample estimates:
mean of the differences
                    3.9</code></pre>
<p>Welche Informationen davon werden benötigt:</p>
<ol type="1">
<li>Name des Tests (Methode): <code>Paired t-test</code></li>
<li>Signifikanz/p-Wert (Verlässlichkeit des Ergebnisses): <code>p-value</code></li>
<li>Effektgrösse und -richtung (unser eigentliches Ergebnis!): <code>mean of the differences</code></li>
<li>ggf. Wert der Teststatistik und Freiheitsgrade (“Zwischenergebnisse”): <code>t</code>, <code>df</code></li>
</ol>
<p>Wichtig ist es, bei aller “Begeisterung” für die p-Werte nicht unser eigentliches Ergebnis zu vergessen, d.&nbsp;h. die Antwort auf die Frage ob die Blüten von A oder von B grösser sind und wenn ja wie stark (blau). Ob Freiheitsgrade und der Wert der Teststatistik angegeben werden müssen, darüber gehen die Geschmäcker auseinander. Wenn man die Daten korrekt in R eingegeben hat, spezifiziert R die Freiheitsgrade automatisch und bei gegebenen Freiheitsgraden ist die Beziehung von t zu p eindeutig. Deshalb genügt es m. E. p anzugeben. (Aber wenn der Betreuer oder die Editorin auch noch t und df haben wollen, dann sollte man sie parat haben). Ein adäquater Satz im Ergebnisteil, der den obigen R output zusammenfasst, lautet daher:</p>
<p>Die Blütengrösse unterschied sich hochsignifikant zwischen den beiden Sorten mit einem Mittelwert von 15.3 cm<sup>2</sup> für Sorte A und 11.4 cm<sup>2</sup> für Sorte B (gepaarter t-Test, <em>p</em> = 0.007, FG = 9).</p>
<section id="oder-auf-englisch" class="level5">
<h5 class="anchored" data-anchor-id="oder-auf-englisch">Oder auf Englisch:</h5>
<p>Flower sizes differed very significantly between the two cultivars with a mean size of 15.3 cm<sup>2</sup> in cultivar A and 11.4 cm<sup>2</sup> in the cultivar B (paired t-test, p = 0.007, df = 9).</p>
</section>
</section>
<section id="text-tabelle-oder-abbildung" class="level4">
<h4 class="anchored" data-anchor-id="text-tabelle-oder-abbildung">Text, Tabelle oder Abbildung?</h4>
<p>Hier kommen ein paar wichtige Vorgaben und Empfehlungen:</p>
<ul>
<li><p>Jedes Ergebnis nur 1x ausführlich darstellen, entweder als Abbildung, in einer Tabelle oder als Text</p></li>
<li><p>Wenn als Abbildung oder Tabelle, dann im Text mit einem zusammenfassenden Statement darauf verweisen, das nicht alle Details wiederholt</p></li>
<li><p>Signifikante und nicht signifikante Ergebnisse berichten</p></li>
<li><p><strong>Gängige Strategie:</strong></p>
<ul>
<li><strong>Abbildungen:</strong> für die wichtigsten signifikanten Ergebnisse</li>
<li><strong>Tabellen:</strong> für die weiteren signifikanten Ergebnisse</li>
<li><strong>Nur Text:</strong> für die nicht signifikanten Ergebnisse</li>
</ul></li>
</ul>
</section>
<section id="abbildungen-in-wissenschaftlichen-arbeiten" class="level4">
<h4 class="anchored" data-anchor-id="abbildungen-in-wissenschaftlichen-arbeiten">Abbildungen in wissenschaftlichen Arbeiten</h4>
<p>Zumindest für die wichtigsten signifikanten Ergebnisse produzieren wir normalerweise Abbildungen. Dabei ist es wichtig, die folgenden Prinzipien zu beherzigen:</p>
<ul>
<li>Abbildungen (und Tabellen) sollten <strong>ohne den zugehörigen Text informativ</strong> sein, d.&nbsp;h. normalerweise <em>p</em>-Werte in der Abbildung/Tabelle bzw. Unter-/ Überschrift angeben</li>
<li><strong>Achsen sind verständlich beschriftet</strong> (ausgeschriebene Variablennamen mit Einheit)</li>
<li><strong>Keine Abbildungsüberschrift</strong> (es gibt die Legende in der Abbildungsunterschrift)</li>
<li>Keine überflüssigen Elemente (z. B. Rahmen, farbiger Hintergrund, horizontale und vertikale Linien)</li>
<li>Klarer <strong>Kontrast</strong>, ausreichende <strong>Linienstärke</strong> und <strong>Schriftgrösse.</strong></li>
</ul>
</section>
<section id="abbildungen-mit-base-r-oder-mit-ggplot2" class="level4">
<h4 class="anchored" data-anchor-id="abbildungen-mit-base-r-oder-mit-ggplot2">Abbildungen mit “base R” oder mit ggplot2?</h4>
<p>Im Folgenden visualisiert mit den Boxplots, die zum <em>t</em>-Test gehören.</p>
<p>In “base R” geht das folgendermassen:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(size<span class="sc">~</span>cultivar, <span class="at">data =</span> blume)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="Statistik_Skript _v.41_SW/_page_34_Figure_0.jpeg" class="img-fluid"></p>
<p>In ggplot2 geht es folgendermassen (mit <em>default</em>-Einstellungen):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(blume, <span class="fu">aes</span>(cultivar, size)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="Statistik_Skript _v.41_SW/_page_35_Figure_0.jpeg" class="img-fluid"></p>
<p>Gut ist, dass die Achsen automatisch beschriftet wurden. Störend ist der graue Hintergrund (reduziert Kontrast) und die weissen Gitternetzlinien (überflüssig und dank des zu geringen Kontrasts eh kaum zu sehen).</p>
<p>Man kann das in ggplot2 durch Wahl des vordefinierten theme_classic optimieren:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(blume, <span class="fu">aes</span>(cultivar, size)) <span class="sc">+</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="Statistik_Skript _v.41_SW/_page_36_Figure_0.jpeg" class="img-fluid"></p>
<p>Das Ergebnis ist insgesamt OK, allerdings sind die Linien zu fein und die Schrift zu klein – jeweils relativ zur Gesamtgrösse der Abbildung.</p>
<p>Man kann weiter optimieren durch Hinzufügen weiterer Steuerelemente (siehe <a href="https://researchmethods-zhaw.github.io/HS25/infovis/Infovis1_Demo.html#themes">https://</a> <a href="https://researchmethods-zhaw.github.io/HS25/infovis/Infovis1_Demo.html#themes">researchmethods-zhaw.github.io/HS25/infovis/Infovis1_Demo.html#themes)</a>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>mytheme <span class="ot">&lt;-</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">linewidth =</span> <span class="fl">0.8</span>, <span class="at">color =</span> <span class="st">"black"</span>), </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>, <span class="at">color =</span> <span class="st">"black"</span>), </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>, <span class="at">color =</span> <span class="st">"black"</span>), </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">axis.ticks =</span> <span class="fu">element_line</span>(<span class="at">linewidth =</span> <span class="fl">0.8</span>, <span class="at">color =</span> <span class="st">"black"</span>), </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">axis.ticks.length =</span> <span class="fu">unit</span>(<span class="fl">0.2</span>, <span class="st">"cm"</span>),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">vjust =</span> <span class="fl">2.5</span>),</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">plot.margin =</span> <span class="fu">margin</span>(<span class="at">t =</span> <span class="fl">5.5</span>, <span class="at">r =</span> <span class="fl">5.5</span>, <span class="at">b =</span> <span class="fl">5.5</span>, <span class="at">l =</span> <span class="dv">7</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(blume, <span class="fu">aes</span>(cultivar, size)) <span class="sc">+</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Cultivar"</span>, <span class="at">y =</span> <span class="st">"Size (cm)"</span>) <span class="sc">+</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>  mytheme</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(blume, <span class="fu">aes</span>(cultivar, size)) <span class="sc">+</span> </span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>  mytheme</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="Statistik_Skript _v.41_SW/_page_37_Figure_1.jpeg" class="img-fluid"></p>
<p>Jetzt passt es… Einzig könnte man noch den <em>p</em>-Wert einblenden</p>
<p>Ob man die Grafiken mit ggplot2 oder base R gestaltet, sei jedem selbst überlassen. Beides hat Vorund Nachteile. Was man aber vermeiden sollte, sind die Ausgaben von ggplot2 mit default-Einstellungen, da diese gängigen Standards für gute Grafiken widerspechen. Hier noch einmal zusammengefasst die Vor- und Nachteile beider Systeme:</p>
<section id="base-r" class="level5">
<h5 class="anchored" data-anchor-id="base-r">Base R:</h5>
<ul>
<li>Einfache Syntax, daher geeignet für schnelles Plotten</li>
<li>ABER: Syntax variiert zwischen verschiedenen Plottbefehlen</li>
<li>ABER: “Finetunen” von Grafiken oftmals umständlich oder gar nicht möglich</li>
<li>Geeignet für Vektoren (ggplot2 braucht dataframes o.ä)</li>
<li>Geeignet für das Plotten von Modellen (plot(lm())</li>
<li>Einfaches Plotten der Modelldiagnostik (plot(summary())</li>
</ul>
</section>
<section id="vorteile-ggplot2" class="level5">
<h5 class="anchored" data-anchor-id="vorteile-ggplot2">Vorteile ggplot2:</h5>
<ul>
<li>Leistungsfähige, universelle Syntax, daher leicht anpassbar an den Bedarf, wenn man das Prinzip erst einmal verstanden hat</li>
<li>Viele Funktionen “out of the box”</li>
<li>Einfachere Gestaltungsmöglichkeit (Farbskalen usw.)</li>
</ul>
</section>
</section>
<section id="inferenzstatistik-vs.-beschreibende-statistik" class="level4">
<h4 class="anchored" data-anchor-id="inferenzstatistik-vs.-beschreibende-statistik">Inferenzstatistik vs.&nbsp;beschreibende Statistik</h4>
<p>In diesem Kapitel ging es um die Frage, wie Statistik beim Hypothesentesten helfen kann. Die statistischen Verfahren, die man dazu anwendet, nennt man <strong>schliessende Statistik</strong> oder <strong>Inferenzstatistik.</strong> Hier wird abgeschätzt, wie wahrscheinlich ein gefundener Effekt in unserer Stichprobe einem tatsächlichen Effekt in der Grundgesamtheit entspricht. Diese Form der Statistik ist in der modernen quantitativen Forschung zentral, egal in welcher Disziplin. Die schliessende Statistik macht daher den Hauptteil des Kurses aus, von Statistik 1 – Statistik 6.</p>
<p>Daneben ist aber auch die <strong>beschreibende</strong> oder <strong>deskriptive Statistik</strong> relevant. Hier geht um die Berechnung statistischer Kenngrössen wie Mittelwert, Median oder Standardabweichung oder die Visualisierung von Werteverteilungen, etwa mittels Boxplots. Wie ihre im Weiteren sehen werdet, wird fast jede inferenzstatistische Untersuchung mit einer deskriptiven Statistik begleitet, sei es in der Form der Angabe von Mittelwerten oder der Visualisierung mittels Boxplots. Daneben gibt es auch Datensätze, die so komplex sind, dass von vornherein das statistische Ziel eine Visualisierung und nicht das Testen von Hypothesen ist. Das betrifft insbesondere die deskriptiv-multivariaten Verfahren, die wir in Statistik 7 und 8 kennenlernen.</p>
</section>
<section id="zusammenfassung" class="level4">
<h4 class="anchored" data-anchor-id="zusammenfassung">Zusammenfassung</h4>
<ul>
<li>Wissenschaftliche Forschung zielt in der Regel entweder auf das <strong>Generieren oder das Testen von Hypothesen</strong>.</li>
<li><strong>Inferenzstatistik</strong> ist das Set statistischer Verfahren (Tests), das sowohl für das Testen als auch das Generieren von Hypothesen) verwendet wird.</li>
<li>Inferenzstatistik ist notwendig, um zu bestimmen, <strong>wie wahrscheinlich ein beobachtetes Muster durch angenommenen Einflussgrössen (Variablen)</strong> und nicht durch (a) Messfehler oder (b) andere “Störgrössen” <strong>hervorgerufen wurde</strong>.</li>
<li>Der <em>p</em><strong>-Wert ist die Wahrscheinlichkeit eines Typ I-Fehlers</strong>, d.&nbsp;h. einen Effekt zu berichten, wo keiner ist; nach üblicher Konvention wird ein Effekt dann als hinreichend sicher (signifikant) angesehen, wenn <em>p</em> &lt; 0.05.</li>
<li>Mit einem <strong>Chi-Quadrat-Test</strong> (oder besser mit Fishers exaktem Test) kann man auf eine <strong>Assoziation zwischen zwei kategorialen Variablen</strong> testen.</li>
<li>Mit einem <em>t</em><strong>-Test kann man</strong> auf <strong>Unterschiede in den Mittelwerten einer metrischen Variablen</strong> zwischen zwei Gruppen testen.</li>
<li><strong>Inferenzstatistik</strong> dient dem Testen von Analysen, <strong>deskriptive Statistik</strong> dem Beschreiben und Visualisieren von Daten.</li>
</ul>
</section>
</section>
<section id="weiterführende-literatur" class="level2">
<h2 class="anchored" data-anchor-id="weiterführende-literatur">Weiterführende Literatur</h2>
<ul>
<li><strong>Crawley, M.J. 2015.</strong> <em>Statistics An introduction using R</em><strong>. 2nd ed.&nbsp;John Wiley &amp; Sons, Chichester, UK: 339 pp.</strong>
<ul>
<li><strong>Chapter 1 Fundamentals</strong></li>
<li><strong>Chapter 6 Two Samples</strong></li>
</ul></li>
<li>Quinn, G.P. &amp; Keough, M.J. 2002. <em>Experimental design and data analysis for biologists</em>. Cambridge University Press, Cambridge, UK: 537 pp.</li>
</ul>


</section>

</main> <!-- /main -->

<script>
    inputs = document.querySelectorAll("pre.sourceCode.r")
    inputs.forEach(function(input){input.parentElement.classList.add("input")})

    outputs = document.querySelectorAll("pre.sourceCode.default, pre.sourceCode.bash")
    outputs.forEach(function(output){output.parentElement.classList.add("output")})

</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopiert");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopiert");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="Vorwort">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Vorwort</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Statistik_2.html" class="pagination-link" aria-label="Statistik 2">
        <span class="nav-page-text"><span class="chapter-title">Statistik 2</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ResearchMethods-ZHAW/Statistik/edit/main/Statistik_1.qmd" class="toc-action"><i class="bi bi-github"></i>Seite editieren</a></li><li><a href="https://github.com/ResearchMethods-ZHAW/Statistik/issues/new" class="toc-action"><i class="bi empty"></i>Problem melden</a></li></ul></div></div></div></footer></body></html>